"""
PySpark batch reconciliation job, submitted as an EMR Serverless job run.

Reads the synthetic accounts/transactions CSVs generated by
generate_synthetic_data.py from S3, computes each account's balance from its
transaction history, and flags accounts where the recorded balance disagrees
with the transaction-derived balance by more than a small epsilon (same
invariant as the daily-reconciliation Lambda, applied here at batch scale
across the full synthetic dataset instead of just the latest transaction).

Usage (as an EMR Serverless job run):
    spark-submit reconciliation_job.py \
        s3://bank-emr-reconciliation-<account_id>/input/accounts.csv \
        s3://bank-emr-reconciliation-<account_id>/input/transactions.csv \
        s3://bank-emr-reconciliation-<account_id>/output/
"""

import sys

from pyspark.sql import SparkSession, functions as F

DISCREPANCY_EPSILON = 0.01


def signed_amount_expr():
    return (
        F.when(F.col("transaction_type").isin("DEPOSIT", "TRANSFER_IN"), F.col("amount"))
        .when(F.col("transaction_type").isin("WITHDRAW", "TRANSFER_OUT"), -F.col("amount"))
        .otherwise(F.lit(0.0))
    )


def compute_discrepancies(accounts_df, transactions_df):
    """Kept separate from I/O so it can be exercised with small in-memory
    DataFrames in tests instead of requiring S3/EMR."""
    net_df = (
        transactions_df.withColumn("signed_amount", signed_amount_expr())
        .groupBy("account_number")
        .agg(F.sum("signed_amount").alias("computed_balance"))
    )

    joined = (
        accounts_df.join(net_df, on="account_number", how="left")
        .fillna({"computed_balance": 0.0})
        .withColumn("difference", F.col("balance") - F.col("computed_balance"))
    )

    return joined.filter(F.abs(F.col("difference")) > DISCREPANCY_EPSILON)


def main(accounts_path, transactions_path, output_path):
    spark = SparkSession.builder.appName("bank-reconciliation").getOrCreate()

    accounts_df = spark.read.option("header", True).option("inferSchema", True).csv(accounts_path)
    transactions_df = spark.read.option("header", True).option("inferSchema", True).csv(transactions_path)

    discrepancies = compute_discrepancies(accounts_df, transactions_df)

    total_accounts = accounts_df.count()
    discrepancy_count = discrepancies.count()
    print(f"Reconciled {total_accounts} accounts, found {discrepancy_count} discrepancies")

    (
        discrepancies.select("account_number", "balance", "computed_balance", "difference")
        .coalesce(1)
        .write.mode("overwrite")
        .option("header", True)
        .csv(output_path)
    )

    spark.stop()


if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: reconciliation_job.py <accounts_path> <transactions_path> <output_path>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2], sys.argv[3])
